"""empty message

Revision ID: 55576e92c519
Revises: 228a4ae6fcff
Create Date: 2024-05-23 18:11:03.622455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55576e92c519'
down_revision = '228a4ae6fcff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_age', sa.Integer(), nullable=False, server_default='0'))

    # Para eliminar el valor por defecto después de la migración, si no lo deseas
    op.alter_column('user_data', 'user_age', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('user_age')

    # ### end Alembic commands ###
