"""empty message

Revision ID: d7ee95702532
Revises: 55576e92c519
Create Date: 2024-05-28 19:29:26.086683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ee95702532'
down_revision = '55576e92c519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('mimetype', sa.String(length=250), nullable=False),
    sa.Column('user_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_data_id'], ['user_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
